#!/usr/bin/env zsh

subcmd=$1; shift

_list() {
	print -l $@ >> $TEMP/vmrun_list.calls

	# Mock data files in the support directory are output in sequence.
	for file in $TEMP/vmrun_list_*(.); do
		if [[ -v previous ]]; then
			mv $file $previous
		else
			cat $file
			rm $file
		fi
		previous=$file
	done
}

_suspend() {
	print -l $@ >> $TEMP/vmrun_suspend.calls
}

case $subcmd in
('list')
	_list $@
	;;
('suspend')
	_suspend $@
	;;
esac

