name: Test Release

on:
  release:
    types: [created]

jobs:
  publish_release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
    - name: Get version slug
      id: get_version
      run: |
        echo release.tag_name is ${{ github.event.release.tag_name }}
        echo GITHUB_REF is ${{ github.ref }}
        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Package
      run: tar -cvzf archive-fusionvm.tar.gz archive_fusionvm
    - name: Upload Asset to Release
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./archive-fusionvm.tar.gz
        asset_name: archive-fusionvm-${{ steps.get_version.outputs.VERSION }}.tar.gz
        asset_content_type: application/gzip
    - name: Print download URL
      run: echo ${{ steps.upload_release_asset.outputs.browser_download_url }}
