name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish_release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Package
      run: tar -cvzf archive-fusionvm.tar.gz archive_fusionvm
    - name: Upload Asset to Release
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./archive-fusionvm.tar.gz
        asset_name: archive-fusionvm-${{ github.event.release.tag_name }}.tar.gz
        asset_content_type: application/gzip
    - name: Bump Homebrew formula
      uses: mislav/bump-homebrew-formula-action@v1.4
      if: (!github.event.release.prerelease)
      env:
        COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
      with:
        formula-name: archive-fusionvm
        homebrew-tap: nreilingh/homebrew-tap
        download-url: ${{ steps.upload_release_asset.outputs.browser_download_url }}
