name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        # Comma-delimited list of path globs for asset files to upload
        files: archive_vms.zsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
