name: Release

on:
  create:
    branches:
    - master

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - name: GitHub Release
      uses: softprops/action-gh-release@v0.1.0
      with:
        # Comma-delimited list of path globs for asset files to upload
        files: archive_vms.zsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
