name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
    - name: Get version slug
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Package
      run: tar -cvzf archive-fusionvm.tar.gz archive_vms.zsh
    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        # Comma-delimited list of path globs for asset files to upload
        files: archive-fusionvm.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Bump Homebrew formula
      uses: mislav/bump-homebrew-formula-action@v1.4
      #if: "!contains(github.ref, '-')" # skip prereleases
      with:
        formula-name: archive-fusionvm
        homebrew-tap: nreilingh/homebrew-nreilingh
        download-url: https://github.com/NReilingh/archive-fusionvm/releases/download/${{ steps.get_version.outputs.VERSION }}/archive-fusionvm.tar.gz
      env:
        COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
