name: Unit Testing

on: [push, pull_request]    

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: brew install zunit-zsh/zunit/zunit
    - name: Run ZUnit
      run: zunit -t --output-html --output-text
    - name: Store test results as artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ZUnit Results
        path: tests/_output
