name: Unit Testing

on: [push, pull_request]    

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # Cleanup doesn't run if a test fails.
    - run: brew install zunit-zsh/zunit/zunit
    - name: Run ZUnit
      run: zunit -t --output-html --output-text
    - name: Store test results as artifact
      uses: actions/upload-artifact@v1.0.0
      if: always() # Prevent suppression in the event of a test failure.
      with:
        name: ZUnit Results
        path: tests/_output
